In [2]:
import math
math.sqrt(16)

4.0

In [1]:
from math import sqrt,pi
print(sqrt(16))
print(sqrt(25))
print(pi)

4.0
5.0
3.141592653589793


In [4]:
from math import sqrt,pi
print(sqrt(16))
print(sqrt(25))
print(pi)

4.0
5.0
3.141592653589793


In [1]:
1+2+3+4+5

15

In [6]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8])
print(ar)


# Create an array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Array operations
print(arr * 2)  # Element-wise multiplication
print(np.mean(arr))  # Mean of the array



[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[ 2  4  6  8 10]
3.0


In [9]:
from math import *
print(sqrt(25))


5.0


In [17]:
import array
arr=array.array('i',[1,2,3,4,5])
print(arr)
type(arr[0])
print(arr[0])

array('i', [1, 2, 3, 4, 5])
1


In [32]:
#random
import random
print(random.random())
print(random.randint(1,1999))
print(random.choice(['apple','banana','cherry']))
numbers = [1, 2, 3, 4, 5]
random.shuffle(numbers)
print(numbers) 
 # Example Output: [3, 5, 1, 4, 2]
random.seed(4)  # Set the seed
print(random.random())  # Same output every time you run this



0.1031660342307158
812
banana
[5, 3, 4, 1, 2]
0.23604808973743452


In [33]:
## files and directory access
import os
print(os.getcwd())

c:\Users\uSER\Desktop\learn py\import modules


In [34]:
os.mkdir('hello')

In [ ]:
## high level operation on files and collection of files
import shutil
shutil 

In [ ]:
import json

data = {
    "name": "Ritika",
    "age": 25,
    "skills": ["Python", "ML"],
    "is_active": True
}

# Convert Python dictionary to JSON
json_data = json.dumps(data)  
print(json_data)
print(type(json_data))
# convert into any kind of data
json_int = json.loads(json_data)
print(json_int)
print(type(json_int))


<class 'str'>
{'name': 'Ritika', 'age': 25, 'skills': ['Python', 'ML'], 'is_active': True}
<class 'dict'>


In [40]:
#csv file format
import csv
with open('example.csv',mode='w',newline='')as file:
    writer=csv.writer(file)
    writer.writerow(['name','age'])
    writer.writerow(['Ritika',20])
    writer.writerow(['Rasmika',14])

with open('example.csv',mode='r')as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)



['name', 'age']
['Ritika', '20']
['Rasmika', '14']


In [41]:
import csv

# Data to write
data = [
    ['name', 'age', 'city'],
    ['Ritika', '25', 'Kathmandu'],
    ['John', '30', 'New York'],
    ['Sara', '28', 'London']
]

# Writing to a CSV file
with open('output.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

print("CSV file written successfully!")


CSV file written successfully!


In [43]:
## date time
from datetime import datetime,timedelta
now=datetime.now()
print(now)
yesterday = now-timedelta(days=1)
print(yesterday)

2025-02-28 13:25:10.611840
2025-02-27 13:25:10.611840


In [44]:
#time
import time
print(time.time())
time.sleep(2)
print(time.time())

1740728472.5020015
1740728474.5025468


In [46]:
# regular expression
import re
pattern = r"\d+"
text = 'there are 123 apples'
match = re.search(pattern,text)
print(match.group())

123
